version: "3.7"
services:
  mongoDatabase:
    image: mongo:4.4-rc
    container_name: mongoDatabase
    hostname: mongoDatabase
    restart: unless-stopped
    ports:
      - "27017:27017"
    networks:
      - main-network
    command: ["--bind_ip", "0.0.0.0"]
  plantIrrigationSerivce:
    build:
      context: .
      dockerfile: Dockerfile
    image: plant-irrigation-service
    container_name: PlantIrrigationService
    hostname: has.prod.plant-irrigation-service
    restart: on-failure
    depends_on:
      - mongoDatabase
    links:
      - mongoDatabase
    ports:
      - "8000:8000"
    expose:
      - "8000"
    networks:
      - main-network
networks:
  main-network:
    name: "PlantNetwork"
    driver: bridge
    ipam:
      config:
        - subnet: 172.25.0.0/24
