version: "3.7"
services:
  plantIrrigationSerivce:
    build:
      context: .
      dockerfile: Dockerfile
    image: plant-irrigation-service
    container_name: PlantIrrigationService
    hostname: has.prod.plant-irrigation-service
    restart: on-failure
    depends_on:
      - mongoDatabase
    ports:
      - "4000:4000"
    networks:
      - main-network
networks:
  default:
    name: "nginx_default"
    external: true
